replicaCount: 1 # HPA 안 쓸 경우 수동 복제 수 지정

image:
  repository: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/aigongbu/service-images
  tag:
  pullPolicy: IfNotPresent

containerPort: 80

service:
  protocol: TCP
  port: 80
  targetPort: 80
  type: ClusterIP

env:
  - name: VITE_NAVER_CLIENT_ID
    value: avCowJdnr6vGSMChndkD
  - name: VITE_NAVER_REDIRECT_URI
    value: http://localhost:8080/login/oauth2/redirect
  - name: VITE_IMP_CODE
    value: imp18800044
  - name: VITE_CHANNEL_KEY
    value: channel-key-c1a1895a-5dfc-41e0-b333-25fc99b11ad8

ingress:
  host: himedia-b.com
  subnets: subnet-0d0377067129f0bc4,subnet-01fd87bdca41defe0
  securityGroups: sg-01aec0238789ac98c
  certificateArn: arn:aws:acm:ap-northeast-2:879381276515:certificate/0dfd4e12-fcd9-4697-b202-d7093d86e8ca