apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: front-service
  template:
    metadata:
      name: front-service
      labels:
        app: front-service
    spec:
      containers:
        - name: front-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: {{ .Values.containerPort }}
