apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        app: {{ .Values.name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          env:
            - name: VITE_NAVER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: front-service-secrets
                  key: VITE_NAVER_CLIENT_ID
            - name: VITE_NAVER_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: front-service-secrets
                  key: VITE_NAVER_REDIRECT_URI
            - name: VITE_IMP_CODE
              valueFrom:
                secretKeyRef:
                  name: front-service-secrets
                  key: VITE_IMP_CODE
            - name: VITE_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: front-service-secrets
                  key: VITE_CHANNEL_KEY
