name: PR Dummy Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  dummy-check:
    runs-on: ubuntu-latest
    name: Build, Push, and Create PR
    steps:
      - name: Dummy step
        run: echo "Dummy check passed"
