name: Build, Push Docker Image, Update Helm Chart, Auto PR + Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: polar-msa-ecr
  IMAGE_TAG: ${{ github.sha }}
  SERVICE_NAME: front-service
  HELM_PATH: helm/front-service/values.yaml

jobs:
  build-push-update:
    if: github.ref == 'refs/heads/main' && !startsWith(github.head_ref, 'update/') && github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    name: Build, Push, and Create PR

    outputs:
      pr-number: ${{ steps.cpr.outputs.pull-request-number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and push Docker image to ECR
        run: |
          docker build -t $SERVICE_NAME:$IMAGE_TAG .
          docker tag $SERVICE_NAME:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Helm values.yaml with new image tag
        run: |
          sed -i "s|tag: .*|tag: $IMAGE_TAG|" $HELM_PATH

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5 # 기본적으로 diff 없으면 PR을 생성하지 않음
        with:
          commit-message: "chore(${{ env.SERVICE_NAME }}): update image tag to $IMAGE_TAG"
          title: "chore(${{ env.SERVICE_NAME }}): update image tag to $IMAGE_TAG"
          body: "Auto-generated PR to update Docker image tag to `${{ github.sha }}`"
          branch: update/${{ env.SERVICE_NAME }}-image-${{ github.sha }}
          base: main
          delete-branch: true

  auto-merge:
    name: Auto Merge PR
    needs: build-push-update
    if: ${{ needs.build-push-update.outputs.pr-number != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          pull-request-number: ${{ needs.build-push-update.outputs.pr-number }}
          merge-method: squash
